version: "3.8"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "weather"
      POSTGRES_USER: "weather"
      POSTGRES_PASSWORD: "weather"
    ports:
      - "55432:5432"