version: "3.8"

services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "weather"
      POSTGRES_USER: "weather"
      POSTGRES_PASSWORD: "weather"
    ports:
      - "55432:5432"

  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: [sh, -c, "alembic upgrade head && python cli.py insert-city && uvicorn project.main:app --reload --host 0.0.0.0"]

  cron:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - postgres
    command: [sh, -c, "touch /var/log/cron.log && service cron start && tail -f /var/log/cron.log"]